[env:webots_simulazione]
platform = native
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    -D SIMULAZIONE_WEBOTS
    -I /usr/local/webots/include/controller/c
    -I /usr/local/webots/include/controller/cpp
    -L /usr/local/webots/lib/controller
    -lController
    -lCppController
    -Wl,-rpath,/usr/local/webots/lib/controller
    -lssl
    -lcrypto

lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
    https://github.com/yhirose/cpp-httplib.git#v0.15.3

#extra_scripts = link_webots.py